version: '2.29.4'

services:

    nginx:
        container_name: nginx
        build: ./nginx
        ports:
            - 443:443
        volumes:
            - nginx_data:/var/www/html
        restart: always
        networks:
            - network

    mariadb:
        container_name: mariadb
        build: ./mariadb
        volumes:
            - 

    wordpress:
        container_name: wordpress
        build: ./wordpress
