version: '2.29.4'

services:

    nginx:
        container_name: nginx
        build: ./requirements/nginx
        dockerfile: Dockerfile
        ports:
            - 443:443
        depends_on:
            - mariadb
            - wordpress

    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        depends_on:
            - mariadb

    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb